In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [98]:
df = pd.read_csv('./alsfrs.csv')

In [99]:
df.head()

,subject_id,Q1_Speech,Q2_Salivation,Q3_Swallowing,Q4_Handwriting,Q5a_Cutting_without_Gastrostomy,Q5b_Cutting_with_Gastrostomy,Q6_Dressing_and_Hygiene,Q7_Turning_in_Bed,Q8_Walking,Q9_Climbing_Stairs,Q10_Respiratory,ALSFRS_Delta,ALSFRS_Total,ALSFRS_R_Total,R_1_Dyspnea,R_2_Orthopnea,R_3_Respiratory_Insufficiency,Mode_of_Administration,ALSFRS_Responded_By
0,329,4.0,3.0,4.0,3.0,2.0,NaN,3.0,2.0,2.0,1.0,3.0,0.0,27.0,NaN,NaN,NaN,NaN,NaN,NaN
1,329,4.0,3.0,4.0,3.0,1.5,NaN,3.0,2.0,2.0,1.0,3.0,8.0,26.5,NaN,NaN,NaN,NaN,NaN,NaN
2,329,4.0,3.0,4.0,3.0,1.0,NaN,3.0,2.0,2.0,1.0,3.0,16.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN
3,329,4.0,3.0,4.0,3.0,3.0,NaN,3.0,3.0,2.0,1.0,4.0,42.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN
4,329,4.0,3.0,4.0,3.0,2.0,NaN,3.0,4.0,2.0,2.0,3.0,72.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN

In [100]:
# merge Q5a and Q5b

df['Q5_Cutting'] = df['Q5a_Cutting_without_Gastrostomy'].fillna(df['Q5b_Cutting_with_Gastrostomy'])

In [101]:
df.head()

,subject_id,Q1_Speech,Q2_Salivation,Q3_Swallowing,Q4_Handwriting,Q5a_Cutting_without_Gastrostomy,Q5b_Cutting_with_Gastrostomy,Q6_Dressing_and_Hygiene,Q7_Turning_in_Bed,Q8_Walking,...,Q10_Respiratory,ALSFRS_Delta,ALSFRS_Total,ALSFRS_R_Total,R_1_Dyspnea,R_2_Orthopnea,R_3_Respiratory_Insufficiency,Mode_of_Administration,ALSFRS_Responded_By,Q5_Cutting
0,329,4.0,3.0,4.0,3.0,2.0,NaN,3.0,2.0,2.0,...,3.0,0.0,27.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0
1,329,4.0,3.0,4.0,3.0,1.5,NaN,3.0,2.0,2.0,...,3.0,8.0,26.5,NaN,NaN,NaN,NaN,NaN,NaN,1.5
2,329,4.0,3.0,4.0,3.0,1.0,NaN,3.0,2.0,2.0,...,3.0,16.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
3,329,4.0,3.0,4.0,3.0,3.0,NaN,3.0,3.0,2.0,...,4.0,42.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
4,329,4.0,3.0,4.0,3.0,2.0,NaN,3.0,4.0,2.0,...,3.0,72.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0

In [102]:
# Fill Q10_Respitory

df['Q10_Respiratory'] = df['Q10_Respiratory'].fillna((df['R_1_Dyspnea'] + df['R_2_Orthopnea'] + df['R_3_Respiratory_Insufficiency']) // 3)

In [103]:
df.head()

,subject_id,Q1_Speech,Q2_Salivation,Q3_Swallowing,Q4_Handwriting,Q5a_Cutting_without_Gastrostomy,Q5b_Cutting_with_Gastrostomy,Q6_Dressing_and_Hygiene,Q7_Turning_in_Bed,Q8_Walking,...,Q10_Respiratory,ALSFRS_Delta,ALSFRS_Total,ALSFRS_R_Total,R_1_Dyspnea,R_2_Orthopnea,R_3_Respiratory_Insufficiency,Mode_of_Administration,ALSFRS_Responded_By,Q5_Cutting
0,329,4.0,3.0,4.0,3.0,2.0,NaN,3.0,2.0,2.0,...,3.0,0.0,27.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0
1,329,4.0,3.0,4.0,3.0,1.5,NaN,3.0,2.0,2.0,...,3.0,8.0,26.5,NaN,NaN,NaN,NaN,NaN,NaN,1.5
2,329,4.0,3.0,4.0,3.0,1.0,NaN,3.0,2.0,2.0,...,3.0,16.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
3,329,4.0,3.0,4.0,3.0,3.0,NaN,3.0,3.0,2.0,...,4.0,42.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
4,329,4.0,3.0,4.0,3.0,2.0,NaN,3.0,4.0,2.0,...,3.0,72.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0

In [104]:
# Fill ALRFS_Total (old gets new)
df['ALSFRS_Total'] = df['ALSFRS_Total'].fillna(df['ALSFRS_R_Total'])

In [105]:
df.iloc[:30].dropna()

Empty DataFrame
Columns: [subject_id, Q1_Speech, Q2_Salivation, Q3_Swallowing, Q4_Handwriting, Q5a_Cutting_without_Gastrostomy, Q5b_Cutting_with_Gastrostomy, Q6_Dressing_and_Hygiene, Q7_Turning_in_Bed, Q8_Walking, Q9_Climbing_Stairs, Q10_Respiratory, ALSFRS_Delta, ALSFRS_Total, ALSFRS_R_Total, R_1_Dyspnea, R_2_Orthopnea, R_3_Respiratory_Insufficiency, Mode_of_Administration, ALSFRS_Responded_By, Q5_Cutting]
Index: []

[0 rows x 21 columns]

In [106]:
# drop Mode_of_administration and responded by
df = df.drop(columns=['Mode_of_Administration', 'ALSFRS_Responded_By', 
                 'R_1_Dyspnea', 'R_2_Orthopnea', 'R_3_Respiratory_Insufficiency', 
                 'ALSFRS_R_Total', 'Q5b_Cutting_with_Gastrostomy', 'Q5a_Cutting_without_Gastrostomy'])

In [107]:
df.head()

,subject_id,Q1_Speech,Q2_Salivation,Q3_Swallowing,Q4_Handwriting,Q6_Dressing_and_Hygiene,Q7_Turning_in_Bed,Q8_Walking,Q9_Climbing_Stairs,Q10_Respiratory,ALSFRS_Delta,ALSFRS_Total,Q5_Cutting
0,329,4.0,3.0,4.0,3.0,3.0,2.0,2.0,1.0,3.0,0.0,27.0,2.0
1,329,4.0,3.0,4.0,3.0,3.0,2.0,2.0,1.0,3.0,8.0,26.5,1.5
2,329,4.0,3.0,4.0,3.0,3.0,2.0,2.0,1.0,3.0,16.0,26.0,1.0
3,329,4.0,3.0,4.0,3.0,3.0,3.0,2.0,1.0,4.0,42.0,30.0,3.0
4,329,4.0,3.0,4.0,3.0,3.0,4.0,2.0,2.0,3.0,72.0,30.0,2.0

In [108]:
df.shape

(60775, 13)

In [109]:
df = df.dropna()

In [110]:
df.insert(5, 'Q5_Cutting1', df['Q5_Cutting'], allow_duplicates=True)

In [111]:
df = df.drop(df.columns[-1], axis=1)

In [112]:
df = df.rename(columns={'Q5_Cutting1': 'Q5_Cutting'})

In [ ]:
def calc_diff(x):
    x['delta_t'] = x['ALSFRS_Delta'].diff()
    return x

# calculate time deltas
df = df.groupby('subject_id').apply(calc_diff)

In [97]:
df.to_csv('alsfrs_cleaned.csv')